version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 8080:15672
      - 5672:5672
  subscriber:
    image: subscriber
    links:
      - rabbitmq
  publisher:
    image: publisher
    links:
      - rabbitmq
    ports:
      - 3000:3000